site_name: Mosh the Subnet
site_url: https://moshthesubnet.com

theme:
  name: material
  palette: 
    - scheme: slate
      primary: indigo
      accent: indigo
  features:
    - navigation.tabs
    - search.suggest

nav:
  - Home: index.md
  - About & Accomplishments: bio.md
  - My Lab: 
      - Overview: lab/overview.md
      - Proxmox: lab/proxmox.md

extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/moshthesubnet
      name: Follow the Pit on Instagram
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/skylerkingnetwork
    - icon: fontawesome/brands/github
      link: https://github.com/moshthesubnet

copyright: |
  &copy; 2026 moshthesubnet. All rights reserved. <br>
  Built with MkDocs and a DIY punk attitude.
