site_name: MoshtheSubnet
site_url: https://moshthesubnet.com

theme:
  name: material
  palette: 
    - scheme: slate
      primary: indigo
      accent: indigo
  features:
    - navigation.tabs
    - search.suggest

nav:
  - Home: index.md
  - About & Accomplishments: bio.md
  - My Lab: 
      - Overview: lab/overview.md
      - Proxmox: lab/proxmox.md
