site_name: Mosh The Subnet
site_url: https://moshthesubnet.com

theme:
  name: material
  palette: 
    - scheme: slate
      primary: red
      accent: deep purple
  features:
    - navigation.tabs
    - search.suggest
    
extra_css:
  - stylesheets/aos.css
  - stylesheets/extra.css

extra_javascript:
  - javascripts/aos.js
  - javascripts/extra.js

nav:
  - Home: index.md
  - About & Accomplishments: bio.md
  - My Lab: 
      - Overview: lab/overview.md
      - Proxmox: lab/proxmox.md
      - Guides:
          - Pi-hole LXC: guides/pihole-lxc.md
      - Projects: 
          - Overview: projects/projects.md
          - VLAN Segmentation: projects/VLAN_segmentation.md
          - Network Topology Diagram: projects/network-topology-diagram.html
          - Local AI Coding Agent: projects/Local_AI_Coding_Agent.md
          - 2-Area OSPF Lab: projects/ospf_lab.md

extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/moshthesubnet
      name: Follow the Pit on Instagram
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/skylerkingnetwork
    - icon: fontawesome/brands/github
      link: https://github.com/moshthesubnet

markdown_extensions:
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - search:  
  - social:
      cards_layout_options:      # ‚Üê needs to be indented under social:
        background_color: "#1e1e2e"
        color: "#b84fff"
        font_family: Roboto
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      zoomFactor: 2  # Allows users to double-click to zoom in closer
  
copyright: |
  &copy; 2026 moshthesubnet. All rights reserved. <br>
  Built with MkDocs and a DIY punk attitude.
