site_name: Mosh The Subnet
site_url: https://moshthesubnet.com

theme:
  name: material
  palette: 
    - scheme: slate
      primary: indigo
      accent: indigo
  features:
    - navigation.tabs
    - search.suggest

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - About & Accomplishments: bio.md
  - My Lab: 
      - Overview: lab/overview.md
      - Proxmox: lab/proxmox.md
      - Guides:
          - Pi-hole LXC: guides/pihole-lxc.md

extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/moshthesubnet
      name: Follow the Pit on Instagram
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/skylerkingnetwork
    - icon: fontawesome/brands/github
      link: https://github.com/moshthesubnet

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  
copyright: |
  &copy; 2026 moshthesubnet. All rights reserved. <br>
  Built with MkDocs and a DIY punk attitude.
